name: Deploy to Netlify

on: 
  push:
    branches:
      - main

jobs:  
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Netlify
          uses: jsmrcaga/action-netlify-deploy@master
          with:
            build_command: npm run build
            build_directory: dist
            NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
            NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
            NETLIFY_DEPLOY_MESSAGE: "Deployed from GitHub action"
            NETLIFY_DEPLOY_TO_PROD: true

      - name: Get live URL
        run: "echo $NETLIFY_LIVE_URL"
